#!/usr/bin/env python

# To save flash space, instead of storing the 
# Y/M/D of the target date, it stores the number
# of days from Jan 1, 2000 until that date.
# This program helps you figure out what that
# number is, so it can be compiled into the sketch.


import sys
import datetime

target = datetime.datetime.strptime(sys.argv[1], "%x")

mtab = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def days_since_jan1_2000(y, m, d):
    t = 0
    for i in range(y-2000):
	t = t + 365
	if i % 4 == 0:
	    t = t + 1 
    for i in range(1, m):
	t = t + mtab[i]
	if y % 4 == 0 and i == 2:
	    t = t + 1 
    t = t + d - 1
    return t

days = days_since_jan1_2000(target.year, target.month, target.day)

print "Add the following line to the platform.ini:"
print
print "build_flags = -Os -DTARGET_DAYS_SINCE_JAN1_2000=%d" % days
