/* AUTOMATICALLY GENERATED */
#define TARGET_YEAR	17
#define TARGET_MONTH	11
#define TARGET_DAY	6
#define TARGET_HOUR	0
#define TARGET_MINUTE	0
#define TARGET_SECOND	0
#define TARGET_DAYS_SINCE_JAN1_2000	6519

